# Generated by Django 4.2.6 on 2026-01-12 03:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_migrate_especialidades_and_alter_fk'),
        ('cit', '0023_remove_especialidad_uc_alter_cita_cubiculo_and_more'),
        ('procedimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0004_paciente_categoria_vip_paciente_enfermedades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolucionConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('motivo_consulta', models.TextField(help_text='Queja principal del paciente')),
                ('hallazgos_clinicos', models.TextField(blank=True, help_text='Hallazgos clínicos encontrados durante la consulta')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones para el paciente')),
                ('cambios_odontograma', models.TextField(blank=True, help_text='Cambios realizados en el odontograma')),
                ('fecha_proximo_control', models.DateField(blank=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolucion', to='cit.cita')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='personal.dentista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Evolución de Consulta',
                'verbose_name_plural': 'Evoluciones de Consulta',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_denticion', models.CharField(choices=[('ADULTO', 'Dentición Adulta (32 piezas)'), ('PEDIÁTRICO', 'Dentición Pediátrica (20 piezas)')], default='ADULTO', max_length=20)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='pacientes.paciente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas_creados', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del plan de tratamiento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del plan')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('URGENTE', 'Urgente'), ('NECESARIO', 'Necesario'), ('ELECTIVO', 'Electivo')], default='NECESARIO', max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_estimada_fin', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(decimal_places=2, help_text='Presupuesto total estimado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('presupuesto_real', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto final real', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='pacientes.paciente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'ordering': ['-prioridad', 'fecha_estimada_fin'],
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoEnEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('observaciones', models.TextField(blank=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('evolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='evolucion.evolucionconsulta')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedimientos.procedimientoodontologico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimiento en Evolución',
                'verbose_name_plural': 'Procedimientos en Evolución',
                'unique_together': {('evolucion', 'procedimiento')},
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinicaOdontologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_medicos', models.TextField(blank=True, help_text='Enfermedades sistémicas, cirugías previas, etc.')),
                ('antecedentes_odontologicos', models.TextField(blank=True, help_text='Procedimientos dentales previos, problemas dentales anteriores, etc.')),
                ('alergias', models.TextField(blank=True, help_text='Alergias a medicamentos, materiales dentales, etc.')),
                ('medicamentos_actuales', models.TextField(blank=True, help_text='Medicamentos que está tomando actualmente')),
                ('fuma', models.BooleanField(default=False, help_text='¿Fuma?')),
                ('consume_alcohol', models.BooleanField(default=False, help_text='¿Consume alcohol?')),
                ('bruxismo', models.BooleanField(default=False, help_text='¿Padece bruxismo (rechina dientes)?')),
                ('frecuencia_cepillado', models.CharField(blank=True, help_text='Frecuencia de cepillado diario (ej: 2-3 veces)', max_length=50)),
                ('usa_seda_dental', models.BooleanField(default=False, help_text='¿Usa seda dental?')),
                ('estado_encias', models.TextField(blank=True, help_text='Observaciones sobre el estado de las encías')),
                ('presencia_sarro', models.BooleanField(default=False)),
                ('presencia_caries', models.BooleanField(default=False)),
                ('observaciones_clinicas', models.TextField(blank=True, help_text='Otras observaciones clínicas relevantes')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica_odontologica', to='pacientes.paciente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas_creadas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia Clínica Odontológica',
                'verbose_name_plural': 'Historias Clínicas Odontológicas',
            },
        ),
        migrations.AddField(
            model_name='evolucionconsulta',
            name='procedimientos_realizados',
            field=models.ManyToManyField(related_name='evoluciones', through='evolucion.ProcedimientoEnEvolucion', to='procedimientos.procedimientoodontologico'),
        ),
        migrations.AddField(
            model_name='evolucionconsulta',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evolucionconsulta',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProcedimientoEnPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, help_text='Orden de ejecución del procedimiento')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio para este procedimiento en el plan', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('realizado', models.BooleanField(default=False)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='evolucion.plantratamiento')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='procedimientos.procedimientoodontologico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_plan_creados', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_plan_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimiento en Plan',
                'verbose_name_plural': 'Procedimientos en Plan',
                'ordering': ['orden'],
                'unique_together': {('plan', 'procedimiento')},
            },
        ),
        migrations.CreateModel(
            name='PiezaDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Número de pieza dental (1-32 adulto, 1-20 pediátrico)')),
                ('nombre_anatomico', models.CharField(help_text='Nombre de la pieza (Incisivo Central Superior Derecho, etc.)', max_length=100)),
                ('estado', models.CharField(choices=[('SANA', 'Sana'), ('CARIES', 'Caries'), ('OBTURADA', 'Obturada'), ('CORONA', 'Corona'), ('IMPLANTE', 'Implante'), ('AUSENTE', 'Ausente'), ('TRATAMIENTO', 'En Tratamiento'), ('FRACTURA', 'Fractura'), ('MOVILIDAD', 'Movilidad')], default='SANA', max_length=20)),
                ('superficies_afectadas', models.CharField(blank=True, help_text="Superficies: O=Oclusal, M=Mesial, D=Distal, V=Vestibular, P=Palatino (ej: 'OM')", max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones clínicas de la pieza')),
                ('fecha_ultima_intervencion', models.DateField(blank=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='evolucion.odontograma')),
                ('procedimiento_realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_tratadas', to='procedimientos.procedimientoodontologico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_creadas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piezas_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pieza Dental',
                'verbose_name_plural': 'Piezas Dentales',
                'ordering': ['numero'],
                'unique_together': {('odontograma', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='evolucionconsulta',
            index=models.Index(fields=['paciente', '-fecha_consulta'], name='evolucion_e_pacient_f78ee3_idx'),
        ),
    ]
