# Generated by Django 4.2.6 on 2025-12-29 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0003_add_sucursal_email_compat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombres', models.CharField(help_text='Nombres del paciente', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Apellidos del paciente', max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(help_text='Número de identificación único', max_length=20, unique=True, verbose_name='Cédula/DNI')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del paciente', verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('telefono', models.CharField(help_text='Número de teléfono principal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico (opcional)', max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(help_text='Dirección de domicilio', verbose_name='Dirección')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, help_text='Alergias conocidas del paciente', verbose_name='Alergias')),
                ('observaciones_medicas', models.TextField(blank=True, help_text='Condiciones médicas, medicamentos, etc.', verbose_name='Observaciones Médicas')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, default='', help_text='Nombre completo del contacto', max_length=150, verbose_name='Nombre del Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, default='', help_text='Teléfono del contacto de emergencia', max_length=20, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia_relacion', models.CharField(blank=True, help_text='Parentesco o relación (Ej: Madre, Esposo)', max_length=50, verbose_name='Relación')),
                ('clinica', models.ForeignKey(blank=True, help_text='Clínica donde está registrado el paciente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinicas.clinica', verbose_name='Clínica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
