# Generated by Django 4.2.6 on 2025-12-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del paciente (opcional)', null=True, upload_to='pacientes/fotos/', verbose_name='Fotografía'),
        ),
    ]
