# Generated by Django 4.2.6 on 2026-01-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enfermedades', '0003_enfermedadpaciente'),
        ('pacientes', '0003_alter_paciente_cedula_alter_paciente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='categoria_vip',
            field=models.CharField(blank=True, choices=[('', 'No VIP'), ('STANDARD', 'VIP Standard'), ('PREMIUM', 'VIP Premium'), ('PLATINUM', 'VIP Platinum')], default='', help_text='Clasificación VIP manual (Standard/Premium/Platinum)', max_length=10, verbose_name='Categoría VIP'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.ManyToManyField(blank=True, help_text='Enfermedades preexistentes asociadas al paciente', related_name='pacientes', through='enfermedades.EnfermedadPaciente', to='enfermedades.enfermedad', verbose_name='Enfermedades'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_vip',
            field=models.BooleanField(default=False, help_text='Marcar manualmente si el paciente es VIP', verbose_name='Cliente VIP'),
        ),
    ]
