# Generated by Django 4.2.6 on 2026-01-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_especialidad_cubiculo'),
        ('pacientes', '0004_paciente_categoria_vip_paciente_enfermedades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(blank=True, db_index=True, help_text='Número de identificación único por clínica', max_length=20, null=True, verbose_name='Cédula/DNI'),
        ),
        migrations.AlterUniqueTogether(
            name='paciente',
            unique_together={('cedula', 'clinica')},
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['cedula', 'clinica'], name='idx_paciente_cedula_clinica'),
        ),
    ]
