# Generated by Django 5.0.6 on 2025-03-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_alter_proveedor_descripcion_comprasenc_comprasdet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprasdet',
            options={'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compras'},
        ),
    ]
