# Generated by assistant to fix field type mismatch: observacion should be CharField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0003_alter_comprasdet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasenc',
            name='observacion',
            field=models.CharField(max_length=250, null=True, blank=True),
        ),
    ]
