# Generated by Django 4.2.6 on 2025-11-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0004_alter_comprasdet_cantidad_alter_comprasdet_costo_and_more'),
        ('cmp', '0004_alter_comprasenc_observacion'),
    ]

    operations = [
    ]
