# Generated by Django 4.2.6 on 2025-11-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0007_alter_comprasdet_costo_alter_comprasdet_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasdet',
            name='costo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='precio_prv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasdet',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comprasenc',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
