# Generated by Django 4.2.6 on 2026-01-12 01:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0006_especialidad_cubiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del procedimiento (ej: RES-OBT001)', max_length=20, unique=True)),
                ('codigo_cdt', models.CharField(blank=True, help_text='Código CDT equivalente (opcional, ej: D2140)', max_length=10, null=True)),
                ('nombre', models.CharField(help_text='Nombre del procedimiento', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del procedimiento')),
                ('categoria', models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico'), ('PREVENTIVA', 'Preventiva'), ('RESTAURATIVA', 'Restaurativa'), ('ENDODONCIA', 'Endodoncia'), ('PERIODONCIA', 'Periodoncia'), ('CIRUGIA', 'Cirugía Oral'), ('PROSTODONCIA', 'Prostodoncia'), ('IMPLANTES', 'Implantes'), ('ORTODONCIA', 'Ortodoncia'), ('URGENCIAS', 'Urgencias'), ('OTROS', 'Otros Servicios')], help_text='Categoría del procedimiento', max_length=50)),
                ('duracion_estimada', models.IntegerField(help_text='Duración estimada en minutos', validators=[django.core.validators.MinValueValidator(5)])),
                ('requiere_anestesia', models.BooleanField(default=False, help_text='¿Requiere anestesia local?')),
                ('afecta_odontograma', models.BooleanField(default=True, help_text='¿Afecta el estado de piezas dentales en el odontograma?')),
                ('estado', models.BooleanField(default=True, help_text='¿Procedimiento activo?')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimiento Odontológico',
                'verbose_name_plural': 'Procedimientos Odontológicos',
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ClinicaProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del procedimiento en la moneda de la clínica', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.CharField(default='USD', help_text='Código de moneda (USD, EUR, etc.)', max_length=3)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activo', models.BooleanField(default=True, help_text='¿Precio activo?')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el precio')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_procedimientos', to='clinicas.clinica')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_por_clinica', to='procedimientos.procedimientoodontologico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_procedimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precios_procedimientos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Precio de Procedimiento por Clínica',
                'verbose_name_plural': 'Precios de Procedimientos por Clínica',
                'ordering': ['clinica', 'procedimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='procedimientoodontologico',
            index=models.Index(fields=['categoria', 'estado'], name='procedimien_categor_8a8ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='procedimientoodontologico',
            index=models.Index(fields=['codigo'], name='procedimien_codigo_a5b453_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaprocedimiento',
            index=models.Index(fields=['clinica', 'activo'], name='procedimien_clinica_6f2179_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicaprocedimiento',
            index=models.Index(fields=['procedimiento', 'activo'], name='procedimien_procedi_6dc5a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicaprocedimiento',
            unique_together={('clinica', 'procedimiento')},
        ),
    ]
