# Generated by Django 4.2.6 on 2026-01-12 05:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_paciente_categoria_vip_paciente_enfermedades_and_more'),
        ('procedimientos', '0001_initial'),
        ('cit', '0023_remove_especialidad_uc_alter_cita_cubiculo_and_more'),
        ('clinicas', '0006_especialidad_cubiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numero_factura', models.CharField(help_text='Número secuencial de factura (FX-YYYY-MM-XXXXX)', max_length=50, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se emitió la factura', verbose_name='Fecha de Emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal sin IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Porcentaje de IVA a aplicar (por defecto 12%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje IVA')),
                ('iva_monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto de IVA calculado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total con IVA', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado a toda la factura', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Pago'), ('PAG', 'Pagada'), ('ANU', 'Anulada')], default='PEN', help_text='Estado actual de la factura', max_length=3, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones sobre la factura', verbose_name='Observaciones')),
                ('cita', models.OneToOneField(blank=True, help_text='Cita que origina la factura (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura', to='cit.cita', verbose_name='Cita Relacionada')),
                ('clinica', models.ForeignKey(help_text='Clínica que emite la factura', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clinicas.clinica', verbose_name='Clínica')),
                ('paciente', models.ForeignKey(help_text='Paciente a quien se factura', on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='pacientes.paciente', verbose_name='Paciente')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal donde se emitió la factura (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='clinicas.sucursal', verbose_name='Sucursal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto pagado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó el pago', verbose_name='Fecha de Pago')),
                ('forma_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta de Crédito/Débito'), ('TRA', 'Transferencia Bancaria'), ('CHE', 'Cheque'), ('SEG', 'Seguro'), ('OTR', 'Otro')], default='EFE', help_text='Forma en que se realizó el pago', max_length=3, verbose_name='Forma de Pago')),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia del pago (número de transacción, cheque, etc.)', max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones sobre el pago', verbose_name='Observaciones')),
                ('factura', models.ForeignKey(help_text='Factura que se está pagando', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.factura', verbose_name='Factura')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['factura'], name='facturacion_factura_a0733c_idx'), models.Index(fields=['fecha_pago'], name='facturacion_fecha_p_8ca3d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de procedimientos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('descuento_item', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Descuento en este ítem', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, help_text='Total del ítem (cantidad × precio - descuento)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del procedimiento', verbose_name='Descripción')),
                ('factura', models.ForeignKey(help_text='Factura a la que pertenece este ítem', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.factura', verbose_name='Factura')),
                ('procedimiento', models.ForeignKey(help_text='Procedimiento odontológico facturado', on_delete=django.db.models.deletion.PROTECT, related_name='items_factura', to='procedimientos.procedimientoodontologico', verbose_name='Procedimiento')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ítem de Factura',
                'verbose_name_plural': 'Ítems de Factura',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['factura'], name='facturacion_factura_15acaa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['paciente', 'clinica'], name='facturacion_pacient_58e646_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='facturacion_estado_b4dd64_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_emision'], name='facturacion_fecha_e_154b8c_idx'),
        ),
    ]
