# Generated by Django 4.2.6 on 2026-01-13 01:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0023_remove_especialidad_uc_alter_cita_cubiculo_and_more'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita que origina la factura (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='cit.cita', verbose_name='Cita Relacionada'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de IVA a aplicar (por defecto 15% - Ecuador)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje IVA'),
        ),
    ]
