# Generated by Django 4.2.6 on 2026-01-13 03:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_factura_cita_alter_factura_iva_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de IVA a aplicar (0% para servicios de salud en Ecuador)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje IVA'),
        ),
    ]
