# Generated by Django 4.2.6 on 2026-01-14 03:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_especialidad_cubiculo'),
        ('personal', '0002_migrate_especialidades_and_alter_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procedimientos', '0001_initial'),
        ('pacientes', '0004_paciente_categoria_vip_paciente_enfermedades_and_more'),
        ('facturacion', '0003_alter_factura_iva_porcentaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha_realizacion', models.DateField(default=django.utils.timezone.now)),
                ('cantidad_realizada', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_facturada', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Facturación'), ('PAR', 'Parcialmente Facturado'), ('FAC', 'Completamente Facturado'), ('ANU', 'Anulado')], default='PEN', max_length=3)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_pendientes', to='clinicas.clinica')),
                ('dentista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_realizados', to='personal.dentista')),
                ('items_factura', models.ManyToManyField(blank=True, related_name='servicios_asociados', to='facturacion.itemfactura')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_pendientes', to='pacientes.paciente')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_pendientes', to='procedimientos.procedimientoodontologico')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio Pendiente',
                'verbose_name_plural': 'Servicios Pendientes',
                'ordering': ['-fecha_realizacion', '-id'],
                'indexes': [models.Index(fields=['paciente', 'clinica'], name='facturacion_pacient_43b2e8_idx'), models.Index(fields=['estado'], name='facturacion_estado_4bacd8_idx'), models.Index(fields=['fecha_realizacion'], name='facturacion_fecha_r_efc5ea_idx')],
            },
        ),
    ]
