# Generated by Django 4.2.6 on 2025-11-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Clínica')),
                ('direccion', models.TextField(help_text='Dirección completa de la clínica principal', verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Teléfono de contacto principal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Email de contacto de la clínica', max_length=254, verbose_name='Email')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Sucursal')),
                ('direccion', models.TextField(help_text='Dirección completa de la sucursal', verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Teléfono de contacto de la sucursal', max_length=20, verbose_name='Teléfono')),
                ('horario_apertura', models.TimeField(help_text='Hora de apertura (formato 24hrs)', verbose_name='Hora de Apertura')),
                ('horario_cierre', models.TimeField(help_text='Hora de cierre (formato 24hrs)', verbose_name='Hora de Cierre')),
                ('dias_atencion', models.CharField(default='Lunes a Viernes', help_text='Ej: Lunes a Viernes, Lunes a Sábado', max_length=50, verbose_name='Días de Atención')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='cit.clinica', verbose_name='Clínica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['clinica', 'nombre'],
                'unique_together': {('clinica', 'nombre')},
            },
        ),
    ]
