# Generated by Django 4.2.6 on 2025-11-11 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Ej: Ortodoncia, Endodoncia, Periodoncia', max_length=100, unique=True, verbose_name='Nombre de la Especialidad')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la especialidad', verbose_name='Descripción')),
                ('duracion_default', models.PositiveIntegerField(default=30, help_text='Duración estimada de una cita de esta especialidad', verbose_name='Duración por Defecto (minutos)')),
                ('color_calendario', models.CharField(default='#3498db', help_text='Color en formato hexadecimal (Ej: #3498db)', max_length=7, verbose_name='Color para Calendario')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cubiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Ej: Consultorio 1, Sala de Cirugía', max_length=100, verbose_name='Nombre del Cubículo')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número identificador del cubículo', verbose_name='Número')),
                ('capacidad', models.PositiveSmallIntegerField(default=2, help_text='Número de personas que pueden estar simultáneamente', verbose_name='Capacidad')),
                ('equipamiento', models.TextField(blank=True, help_text='Descripción del equipamiento disponible', verbose_name='Equipamiento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubiculos', to='cit.sucursal', verbose_name='Sucursal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cubículo',
                'verbose_name_plural': 'Cubículos',
                'ordering': ['sucursal', 'numero'],
                'unique_together': {('sucursal', 'numero')},
            },
        ),
    ]
