# Generated by Django 4.2.6 on 2025-11-11 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit', '0002_especialidad_cubiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cedula_profesional', models.CharField(help_text='Número de cédula profesional de odontología', max_length=20, unique=True, verbose_name='Cédula Profesional')),
                ('numero_licencia', models.CharField(help_text='Número de licencia para ejercer', max_length=30, unique=True, verbose_name='Número de Licencia')),
                ('telefono_movil', models.CharField(help_text='Número de teléfono móvil personal', max_length=20, verbose_name='Teléfono Móvil')),
                ('fecha_contratacion', models.DateField(help_text='Fecha en que inició labores', verbose_name='Fecha de Contratación')),
                ('biografia', models.TextField(blank=True, help_text='Descripción profesional, estudios, experiencia', verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, help_text='Foto del dentista', null=True, upload_to='dentistas/fotos/', verbose_name='Fotografía')),
                ('especialidades', models.ManyToManyField(help_text='Especialidades que practica el dentista', related_name='dentistas', to='cit.especialidad', verbose_name='Especialidades')),
                ('sucursal_principal', models.ForeignKey(blank=True, help_text='Sucursal donde trabaja principalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentistas', to='cit.sucursal', verbose_name='Sucursal Principal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(help_text='Usuario del sistema asociado al dentista', on_delete=django.db.models.deletion.CASCADE, related_name='dentista_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
    ]
