# Generated by Django 4.2.6 on 2025-11-11 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit', '0004_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora de inicio de la cita', verbose_name='Fecha y Hora')),
                ('duracion', models.PositiveIntegerField(default=30, help_text='Duración estimada en minutos', verbose_name='Duración (minutos)')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('CON', 'Confirmada'), ('ATE', 'En Atención'), ('COM', 'Completada'), ('CAN', 'Cancelada'), ('NAS', 'No Asistió')], default='PEN', help_text='Estado actual de la cita', max_length=3, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, help_text='Notas u observaciones sobre la cita', verbose_name='Observaciones')),
                ('motivo_cancelacion', models.TextField(blank=True, help_text='Razón por la cual se canceló la cita', verbose_name='Motivo de Cancelación')),
                ('cubiculo', models.ForeignKey(help_text='Cubículo donde se realizará la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='cit.cubiculo', verbose_name='Cubículo')),
                ('dentista', models.ForeignKey(help_text='Dentista que atenderá la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='cit.dentista', verbose_name='Dentista')),
                ('especialidad', models.ForeignKey(help_text='Especialidad odontológica de la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='cit.especialidad', verbose_name='Especialidad')),
                ('paciente', models.ForeignKey(help_text='Paciente que tiene la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='cit.paciente', verbose_name='Paciente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora', 'estado'], name='cit_cita_fecha_h_a79f8f_idx'), models.Index(fields=['dentista', 'fecha_hora'], name='cit_cita_dentist_d46588_idx'), models.Index(fields=['paciente', 'fecha_hora'], name='cit_cita_pacient_1f0a01_idx')],
            },
        ),
    ]
