# Generated by Django 4.2.6 on 2025-11-12 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit', '0005_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('tipo', models.CharField(choices=[('VACA', 'Vacaciones'), ('FERIA', 'Feriado'), ('LIBRE', 'Día Libre'), ('CAPAC', 'Capacitación'), ('OTRO', 'Otro')], default='LIBRE', max_length=10, verbose_name='Tipo')),
                ('motivo', models.TextField(blank=True, help_text='Descripción del motivo de la excepción', verbose_name='Motivo')),
                ('todo_el_dia', models.BooleanField(default=True, help_text='Si está marcado, no se atiende en todo el día', verbose_name='Todo el Día')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Si no es todo el día, especificar hora de inicio de la excepción', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Si no es todo el día, especificar hora de fin de la excepción', null=True, verbose_name='Hora de Fin')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='cit.dentista', verbose_name='Dentista')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de Disponibilidad',
                'verbose_name_plural': 'Excepciones de Disponibilidad',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('horario_inicio', models.TimeField(default='08:30:00', help_text='Hora de inicio de atención (ej: 08:30)', verbose_name='Hora de Inicio')),
                ('horario_fin', models.TimeField(default='18:00:00', help_text='Hora límite para iniciar última cita (ej: 18:00)', verbose_name='Hora de Fin')),
                ('duracion_slot', models.PositiveIntegerField(default=30, help_text='Intervalo de tiempo en el calendario (15, 30, 60 minutos)', verbose_name='Duración de Slot (minutos)')),
                ('atiende_lunes', models.BooleanField(default=True, verbose_name='Lunes')),
                ('atiende_martes', models.BooleanField(default=True, verbose_name='Martes')),
                ('atiende_miercoles', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('atiende_jueves', models.BooleanField(default=True, verbose_name='Jueves')),
                ('atiende_viernes', models.BooleanField(default=True, verbose_name='Viernes')),
                ('atiende_sabado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('atiende_domingo', models.BooleanField(default=False, verbose_name='Domingo')),
                ('sabado_hora_inicio', models.TimeField(blank=True, default='08:30:00', null=True, verbose_name='Sábado - Hora Inicio')),
                ('sabado_hora_fin', models.TimeField(blank=True, default='12:00:00', null=True, verbose_name='Sábado - Hora Fin')),
                ('permitir_citas_mismo_dia', models.BooleanField(default=True, help_text='Si está habilitado, se pueden agendar citas para el día actual', verbose_name='Permitir Citas el Mismo Día')),
                ('horas_anticipacion_minima', models.PositiveIntegerField(default=0, help_text='Horas mínimas de anticipación para agendar (0 = inmediato)', verbose_name='Horas de Anticipación Mínima')),
                ('sucursal', models.OneToOneField(help_text='Sucursal a la que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='cit.sucursal', verbose_name='Sucursal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Clínica',
                'verbose_name_plural': 'Configuraciones de Clínica',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de atención', verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de atención', verbose_name='Hora de Fin')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se usa este horario', verbose_name='Activo')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='cit.dentista', verbose_name='Dentista')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Dentista',
                'verbose_name_plural': 'Disponibilidades de Dentistas',
                'ordering': ['dentista', 'dia_semana', 'hora_inicio'],
                'unique_together': {('dentista', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
