# Generated by Django 4.2.6 on 2025-11-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0006_excepciondisponibilidad_configuracionclinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentista',
            name='sucursales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales donde el dentista puede atender', related_name='dentistas_asignados', to='cit.sucursal', verbose_name='Sucursales'),
        ),
    ]
