# Generated by Django 4.2.6 on 2025-11-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0007_dentista_sucursales'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilidaddentista',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disponibilidaddentista',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde atiende en este horario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_dentistas', to='cit.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidaddentista',
            unique_together={('dentista', 'sucursal', 'dia_semana', 'hora_inicio')},
        ),
    ]
