# Generated by Django 4.2.6 on 2025-11-14 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit', '0008_alter_disponibilidaddentista_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('tipo_comision', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('FIJO', 'Valor Fijo ($)')], default='PORCENTAJE', help_text='Tipo de comisión: Porcentaje o Valor Fijo', max_length=10, verbose_name='Tipo de Comisión')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión (Ej: 15.50 para 15.50%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Porcentaje (%)')),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fijo de comisión por tratamiento (Ej: 50.00)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Fijo ($)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración de comisión está activa', verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre esta comisión', verbose_name='Observaciones')),
                ('dentista', models.ForeignKey(help_text='Dentista al que se le asigna la comisión', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='cit.dentista', verbose_name='Dentista')),
                ('especialidad', models.ForeignKey(help_text='Especialidad sobre la que se aplica la comisión', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='cit.especialidad', verbose_name='Especialidad')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comisión de Dentista',
                'verbose_name_plural': 'Comisiones de Dentistas',
                'ordering': ['dentista', 'especialidad'],
                'unique_together': {('dentista', 'especialidad')},
            },
        ),
    ]
