# Generated by Django 4.2.6 on 2025-11-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0009_comisiondentista'),
    ]

    operations = [
    ]
