# Generated by Django 4.2.6 on 2025-11-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0010_remove_unique_together_comision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comisiondentista',
            unique_together=set(),
        ),
    ]
