# Generated by Django 4.2.6 on 2025-11-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0011_remove_unique_together_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la clínica (opcional)', null=True, upload_to='clinicas/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('PEN', 'Sol Peruano'), ('COP', 'Peso Colombiano'), ('MXN', 'Peso Mexicano'), ('CLP', 'Peso Chileno'), ('ARS', 'Peso Argentino')], default='USD', help_text='Moneda de operación', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='pais',
            field=models.CharField(choices=[('EC', 'Ecuador'), ('PE', 'Perú'), ('CO', 'Colombia'), ('MX', 'México'), ('CL', 'Chile'), ('AR', 'Argentina')], default='EC', help_text='País donde opera la clínica', max_length=2, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal de la empresa para facturas', max_length=200, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='representante_legal',
            field=models.CharField(blank=True, help_text='Nombre completo del representante legal', max_length=150, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='ruc',
            field=models.CharField(blank=True, help_text='Número de identificación fiscal según país', max_length=20, null=True, verbose_name='RUC/NIT/CUIT'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL del sitio web oficial (opcional)', null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='zona_horaria',
            field=models.CharField(default='America/Guayaquil', help_text='Zona horaria del país (ej: America/Guayaquil)', max_length=50, verbose_name='Zona Horaria'),
        ),
    ]
