# Generated by Django 4.2.6 on 2025-12-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_alter_sucursal_horario_apertura_and_more'),
        ('cit', '0013_horarios_diferenciados'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sucursal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='uc',
        ),
        migrations.AlterField(
            model_name='configuracionclinica',
            name='sucursal',
            field=models.OneToOneField(help_text='Sucursal a la que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='clinicas.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='cubiculo',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cubiculos', to='clinicas.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='fecha_contratacion',
            field=models.DateField(blank=True, help_text='Fecha en que inició labores', null=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='sucursal_principal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde trabaja principalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentistas', to='clinicas.sucursal', verbose_name='Sucursal Principal'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='sucursales',
            field=models.ManyToManyField(blank=True, help_text='Sucursales donde el dentista puede atender', related_name='dentistas_asignados', to='clinicas.sucursal', verbose_name='Sucursales'),
        ),
        migrations.AlterField(
            model_name='disponibilidaddentista',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde atiende en este horario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_dentistas', to='clinicas.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(help_text='Clínica donde está registrado el paciente', on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinicas.clinica', verbose_name='Clínica'),
        ),
        migrations.DeleteModel(
            name='Clinica',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
