# Generated by Django 4.2.6 on 2025-12-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0014_alter_sucursal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubiculo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción breve del cubículo', verbose_name='Descripción'),
        ),
    ]
