# Generated by Django 4.2.6 on 2025-12-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0015_cubiculo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubiculo',
            name='numero',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número identificador del cubículo', null=True, verbose_name='Número'),
        ),
    ]
