# Generated by Django 4.2.6 on 2025-12-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_alter_sucursal_horario_apertura_and_more'),
        ('cit', '0016_alter_cubiculo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(blank=True, help_text='Clínica donde está registrado el paciente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinicas.clinica', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre completo del contacto', max_length=150, verbose_name='Nombre del Contacto de Emergencia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, default='', help_text='Teléfono del contacto de emergencia', max_length=20, verbose_name='Teléfono de Emergencia'),
        ),
    ]
