# Generated by Django 4.2.6 on 2025-12-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0017_alter_paciente_clinica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='numero_licencia',
            field=models.CharField(blank=True, help_text='Número de licencia para ejercer', max_length=30, null=True, verbose_name='Número de Licencia'),
        ),
        migrations.AddConstraint(
            model_name='dentista',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_licencia__isnull', False)), fields=('numero_licencia',), name='unique_numero_licencia_non_null'),
        ),
    ]
