# Generated by Django 4.2.6 on 2025-12-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0018_alter_dentista_numero_licencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='uc',
        ),
    ]
