# Generated by Django 4.2.6 on 2025-12-29 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('cit', '0019_remove_paciente_clinica_remove_paciente_uc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(help_text='Paciente que tiene la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
