# Generated by Django 4.2.6 on 2025-12-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cit', '0020_alter_cita_paciente_delete_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisiondentista',
            name='dentista',
        ),
        migrations.RemoveField(
            model_name='comisiondentista',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='comisiondentista',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='sucursal_principal',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='sucursales',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='dentista',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidaddentista',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disponibilidaddentista',
            name='dentista',
        ),
        migrations.RemoveField(
            model_name='disponibilidaddentista',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='disponibilidaddentista',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='excepciondisponibilidad',
            name='dentista',
        ),
        migrations.RemoveField(
            model_name='excepciondisponibilidad',
            name='uc',
        ),
    ]
