# Generated by Django 4.2.6 on 2025-12-29 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        ('cit', '0021_remove_comisiondentista_dentista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dentista',
            field=models.ForeignKey(help_text='Dentista que atenderá la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='personal.dentista', verbose_name='Dentista'),
        ),
        migrations.DeleteModel(
            name='ComisionDentista',
        ),
        migrations.DeleteModel(
            name='Dentista',
        ),
        migrations.DeleteModel(
            name='DisponibilidadDentista',
        ),
        migrations.DeleteModel(
            name='ExcepcionDisponibilidad',
        ),
    ]
