# Generated by Django 4.2.6 on 2026-01-10 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_migrate_especialidades_and_alter_fk'),
        ('clinicas', '0006_especialidad_cubiculo'),
        ('cit', '0022_alter_cita_dentista_delete_comisiondentista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='uc',
        ),
        migrations.AlterField(
            model_name='cita',
            name='cubiculo',
            field=models.ForeignKey(help_text='Cubículo donde se realizará la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clinicas.cubiculo', verbose_name='Cubículo'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(help_text='Especialidad odontológica de la cita', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clinicas.especialidad', verbose_name='Especialidad'),
        ),
        migrations.DeleteModel(
            name='Cubiculo',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
