# Generated by Django 4.2.6 on 2026-01-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0006_especialidad_cubiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_clinica', 'Administrador de Clínica'), ('administrativo', 'Personal Administrativo'), ('odontologo', 'Odontólogo'), ('asistente', 'Asistente Odontológico')], default='administrativo', max_length=20, verbose_name='Rol del usuario')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Usuario activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última modificación')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='clinicas.clinica')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinica_asignacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Clínica',
                'verbose_name_plural': 'Usuarios-Clínicas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['clinica', 'rol'], name='usuarios_us_clinica_d989f5_idx'), models.Index(fields=['usuario', 'activo'], name='usuarios_us_usuario_09310d_idx')],
                'unique_together': {('usuario', 'clinica')},
            },
        ),
    ]
