# Generated by Django 4.2.6 on 2026-01-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_especialidad_cubiculo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioclinica',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal principal donde trabaja el usuario (opcional). Admin de Clínica no tiene sucursal asignada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_asignados', to='clinicas.sucursal', verbose_name='Sucursal Asignada'),
        ),
        migrations.AlterField(
            model_name='usuarioclinica',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_clinica', 'Administrador de Clínica'), ('dentista', 'Dentista'), ('auxiliar', 'Auxiliar Odontológico'), ('recepcionista', 'Recepcionista'), ('administrativo', 'Personal Administrativo'), ('odontologo', 'Odontólogo'), ('asistente', 'Asistente Odontológico')], default='administrativo', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
