# Generated by Django 4.2.6 on 2026-01-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0006_especialidad_cubiculo'),
        ('usuarios', '0002_usuarioclinica_sucursal_alter_usuarioclinica_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único (ej: recepcion.crear_cita, odontologia.editar_diagnostico)', max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('recepcion', 'Recepción'), ('asistencia', 'Asistencia Odontológica'), ('odontologia', 'Odontología'), ('admin', 'Administración'), ('reportes', 'Reportes'), ('inventario', 'Inventario'), ('facturacion', 'Facturación')], max_length=50, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Vacío = Permiso global. Seleccionar = Permiso personalizado para esta clínica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_personalizados', to='clinicas.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Permiso Personalizado',
                'verbose_name_plural': 'Permisos Personalizados',
                'db_table': 'usuarios_permiso_personalizado',
                'ordering': ['categoria', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='usuarioclinica',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('admin_clinica', 'Administrador de Clínica'), ('dentista', 'Dentista'), ('auxiliar', 'Auxiliar Odontológico'), ('recepcionista', 'Recepcionista'), ('administrativo', 'Personal Administrativo'), ('odontologo', 'Odontólogo'), ('asistente', 'Asistente Odontológico')], default='administrativo', help_text='Campo antiguo. Usar "roles_personalizados" para nueva funcionalidad.', max_length=20, verbose_name='Rol del usuario (Legacy)'),
        ),
        migrations.CreateModel(
            name='RolUsuarioDentalForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de las responsabilidades de este rol', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(blank=True, help_text='Vacío = Rol global. Seleccionar = Rol personalizado para esta clínica', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_personalizados', to='clinicas.clinica', verbose_name='Clínica')),
                ('permisos', models.ManyToManyField(blank=True, related_name='roles', to='usuarios.permisopersonalizado', verbose_name='Permisos asignados a este rol')),
            ],
            options={
                'verbose_name': 'Rol DentalForce',
                'verbose_name_plural': 'Roles DentalForce',
                'db_table': 'usuarios_rol_dentalforce',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuarioclinica',
            name='permisos_adicionales',
            field=models.ManyToManyField(blank=True, help_text='Permisos adicionales específicos. Se suman a los permisos de los roles.', related_name='usuarios_con_permiso_adicional', to='usuarios.permisopersonalizado', verbose_name='Permisos Adicionales'),
        ),
        migrations.AddField(
            model_name='usuarioclinica',
            name='roles_personalizados',
            field=models.ManyToManyField(blank=True, help_text='Nuevos roles con permisos granulares. Puede asignar múltiples roles.', related_name='usuarios_asignados', to='usuarios.rolusuariodentalforce', verbose_name='Roles Personalizados'),
        ),
        migrations.AddIndex(
            model_name='rolusuariodentalforce',
            index=models.Index(fields=['nombre', 'activo'], name='usuarios_ro_nombre_29a220_idx'),
        ),
        migrations.AddIndex(
            model_name='rolusuariodentalforce',
            index=models.Index(fields=['clinica'], name='usuarios_ro_clinica_bab30a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolusuariodentalforce',
            unique_together={('clinica', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='permisopersonalizado',
            index=models.Index(fields=['codigo', 'activo'], name='usuarios_pe_codigo_332e41_idx'),
        ),
        migrations.AddIndex(
            model_name='permisopersonalizado',
            index=models.Index(fields=['clinica', 'activo'], name='usuarios_pe_clinica_86a6d3_idx'),
        ),
        migrations.AddIndex(
            model_name='permisopersonalizado',
            index=models.Index(fields=['categoria'], name='usuarios_pe_categor_6d3423_idx'),
        ),
    ]
