# Generated by Django 4.2.6 on 2026-01-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_permisopersonalizado_alter_usuarioclinica_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioclinica',
            name='contrasena_temporal',
            field=models.BooleanField(default=False, help_text='Marca si el usuario tiene una contraseña temporal y debe cambiarla en primer acceso', verbose_name='¿Contraseña temporal?'),
        ),
    ]
