# Generated by Django 4.2.6 on 2025-12-29 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0003_add_sucursal_email_compat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cit', '0021_remove_comisiondentista_dentista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('cedula_profesional', models.CharField(help_text='Número de cédula profesional de odontología', max_length=20, unique=True, verbose_name='Cédula Profesional')),
                ('numero_licencia', models.CharField(blank=True, help_text='Número de licencia para ejercer', max_length=30, null=True, verbose_name='Número de Licencia')),
                ('telefono_movil', models.CharField(help_text='Número de teléfono móvil personal', max_length=20, verbose_name='Teléfono Móvil')),
                ('fecha_contratacion', models.DateField(blank=True, help_text='Fecha en que inició labores', null=True, verbose_name='Fecha de Contratación')),
                ('biografia', models.TextField(blank=True, help_text='Descripción profesional, estudios, experiencia', verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, help_text='Foto del dentista', null=True, upload_to='dentistas/fotos/', verbose_name='Fotografía')),
                ('especialidades', models.ManyToManyField(help_text='Especialidades que practica el dentista', related_name='dentistas', to='cit.especialidad', verbose_name='Especialidades')),
                ('sucursal_principal', models.ForeignKey(blank=True, help_text='Sucursal donde trabaja principalmente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentistas', to='clinicas.sucursal', verbose_name='Sucursal Principal')),
                ('sucursales', models.ManyToManyField(blank=True, help_text='Sucursales donde el dentista puede atender', related_name='dentistas_asignados', to='clinicas.sucursal', verbose_name='Sucursales')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(help_text='Usuario del sistema asociado al dentista', on_delete=django.db.models.deletion.CASCADE, related_name='dentista_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('tipo', models.CharField(choices=[('VACA', 'Vacaciones'), ('FERIA', 'Feriado'), ('LIBRE', 'Día Libre'), ('CAPAC', 'Capacitación'), ('OTRO', 'Otro')], default='LIBRE', max_length=10, verbose_name='Tipo')),
                ('motivo', models.TextField(blank=True, help_text='Descripción del motivo de la excepción', verbose_name='Motivo')),
                ('todo_el_dia', models.BooleanField(default=True, help_text='Si está marcado, no se atiende en todo el día', verbose_name='Todo el Día')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Si no es todo el día, especificar hora de inicio de la excepción', null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, help_text='Si no es todo el día, especificar hora de fin de la excepción', null=True, verbose_name='Hora de Fin')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='personal.dentista', verbose_name='Dentista')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de Disponibilidad',
                'verbose_name_plural': 'Excepciones de Disponibilidad',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ComisionDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('tipo_comision', models.CharField(choices=[('PORCENTAJE', 'Porcentaje (%)'), ('FIJO', 'Valor Fijo ($)')], default='PORCENTAJE', help_text='Tipo de comisión: Porcentaje o Valor Fijo', max_length=10, verbose_name='Tipo de Comisión')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión (Ej: 15.50 para 15.50%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Porcentaje (%)')),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fijo de comisión por tratamiento (Ej: 50.00)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Valor Fijo ($)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración de comisión está activa', verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre esta comisión', verbose_name='Observaciones')),
                ('dentista', models.ForeignKey(help_text='Dentista al que se le asigna la comisión', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='personal.dentista', verbose_name='Dentista')),
                ('especialidad', models.ForeignKey(help_text='Especialidad sobre la que se aplica la comisión', on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='cit.especialidad', verbose_name='Especialidad')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comisión de Dentista',
                'verbose_name_plural': 'Comisiones de Dentistas',
                'ordering': ['dentista', 'especialidad'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadDentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio de atención', verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(help_text='Hora de fin de atención', verbose_name='Hora de Fin')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se usa este horario', verbose_name='Activo')),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='personal.dentista', verbose_name='Dentista')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal donde atiende en este horario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_dentistas', to='clinicas.sucursal', verbose_name='Sucursal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Dentista',
                'verbose_name_plural': 'Disponibilidades de Dentistas',
                'ordering': ['dentista', 'dia_semana', 'hora_inicio'],
                'unique_together': {('dentista', 'sucursal', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.AddConstraint(
            model_name='dentista',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_licencia__isnull', False)), fields=('numero_licencia',), name='unique_numero_licencia_personal'),
        ),
    ]
