# Generated by Django 4.2.6 on 2026-01-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_migrate_especialidades_and_alter_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentista',
            name='cedula_profesional',
            field=models.CharField(blank=True, help_text='Número de cédula profesional de odontología', max_length=20, null=True, unique=True, verbose_name='Cédula Profesional'),
        ),
        migrations.AlterField(
            model_name='dentista',
            name='telefono_movil',
            field=models.CharField(blank=True, help_text='Número de teléfono móvil personal', max_length=20, null=True, verbose_name='Teléfono Móvil'),
        ),
    ]
