# Generated by Django 4.2.6 on 2026-01-29 15:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0006_especialidad_cubiculo'),
        ('personal', '0003_alter_dentista_cedula_profesional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('tipo_personal', models.CharField(choices=[('administrativo', 'Administrativo'), ('auxiliar', 'Auxiliar'), ('asistente', 'Asistente'), ('recepcion', 'Recepción'), ('servicios', 'Servicios Generales')], default='auxiliar', max_length=20, verbose_name='Tipo de Personal')),
                ('tipo_compensacion', models.CharField(choices=[('MENSUAL', 'Mensual (Salario fijo)'), ('POR_HORA', 'Pago por hora'), ('POR_DIA', 'Pago por día')], default='MENSUAL', max_length=10, verbose_name='Tipo de Compensación')),
                ('salario_mensual', models.DecimalField(decimal_places=2, default=Decimal('482.00'), help_text='Salario mensual (SBU por defecto)', max_digits=10, verbose_name='Salario Mensual')),
                ('tarifa_por_hora', models.DecimalField(blank=True, decimal_places=2, help_text='Usar si la compensación es por hora', max_digits=10, null=True, verbose_name='Tarifa por Hora')),
                ('tarifa_por_dia', models.DecimalField(blank=True, decimal_places=2, help_text='Usar si la compensación es por día', max_digits=10, null=True, verbose_name='Tarifa por Día')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('sucursal_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_principal', to='clinicas.sucursal', verbose_name='Sucursal Principal')),
                ('sucursales', models.ManyToManyField(blank=True, help_text='Sucursales donde puede trabajar', related_name='personal_asignado', to='clinicas.sucursal', verbose_name='Sucursales')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(help_text='Usuario del sistema asociado al personal', on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHorasPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('tipo_extra', models.CharField(choices=[('RECARGO_25', 'Extra 25% (después de 18:00)'), ('RECARGO_50', 'Extra 50% (después de 20:00)'), ('RECARGO_100', 'Extra 100% (feriados/domingo)'), ('SABADO_MEDIO_DIA', 'Sábado medio día (USD 20)')], default='RECARGO_25', max_length=20, verbose_name='Tipo de Extra')),
                ('horas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Horas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('aprobado_en', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado en')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_horas_personal', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extra', to='personal.personal', verbose_name='Personal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Horas Extra',
                'verbose_name_plural': 'Registros de Horas Extra',
                'ordering': ['-fecha', 'personal'],
            },
        ),
        migrations.CreateModel(
            name='ExcepcionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('PERMISO', 'Permiso'), ('CAPACITACION', 'Capacitación'), ('OTRO', 'Otro')], default='PERMISO', max_length=15)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='personal.personal', verbose_name='Personal')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Excepción de Personal',
                'verbose_name_plural': 'Excepciones de Personal',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
