# Generated by Django 4.2.6 on 2026-01-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_personal_registrohoraspersonal_excepcionpersonal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraspersonal',
            name='es_desglosado',
            field=models.BooleanField(default=False, help_text='True si este registro fue creado automáticamente por desglose de tiempo nocturno', verbose_name='Es Desglosado'),
        ),
        migrations.AddField(
            model_name='registrohoraspersonal',
            name='registro_padre',
            field=models.ForeignKey(blank=True, help_text='Registro original si este fue desglosado automáticamente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_desglosados', to='personal.registrohoraspersonal', verbose_name='Registro Padre'),
        ),
    ]
