# Generated by Django 4.2.6 on 2025-12-28 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Clínica')),
                ('direccion', models.TextField(help_text='Dirección completa de la clínica principal', verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Teléfono de contacto principal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Email de contacto de la clínica', max_length=254, verbose_name='Email')),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC/NIT/CUIT')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('representante_legal', models.CharField(blank=True, max_length=150, null=True, verbose_name='Representante Legal')),
                ('pais', models.CharField(choices=[('EC', 'Ecuador'), ('PE', 'Perú'), ('CO', 'Colombia'), ('MX', 'México'), ('CL', 'Chile'), ('AR', 'Argentina')], default='EC', max_length=2, verbose_name='País')),
                ('moneda', models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('PEN', 'Sol Peruano'), ('COP', 'Peso Colombiano'), ('MXN', 'Peso Mexicano'), ('CLP', 'Peso Chileno'), ('ARS', 'Peso Argentino')], default='USD', max_length=3, verbose_name='Moneda')),
                ('zona_horaria', models.CharField(default='America/Guayaquil', max_length=50, verbose_name='Zona Horaria')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinicas/logos/', verbose_name='Logo')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'db_table': 'clinicas_clinica',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Sucursal')),
                ('direccion', models.TextField(help_text='Dirección completa de la sucursal', verbose_name='Dirección')),
                ('telefono', models.CharField(help_text='Teléfono de contacto de la sucursal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Email de contacto de la sucursal', max_length=254, null=True, verbose_name='Email')),
                ('horario_apertura', models.TimeField(verbose_name='Hora de Apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Hora de Cierre')),
                ('dias_atencion', models.CharField(default='Lunes a Viernes', max_length=50, verbose_name='Días de Atención')),
                ('sabado_horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Sábado - Hora de Apertura')),
                ('sabado_horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Sábado - Hora de Cierre')),
                ('domingo_horario_apertura', models.TimeField(blank=True, null=True, verbose_name='Domingo - Hora de Apertura')),
                ('domingo_horario_cierre', models.TimeField(blank=True, null=True, verbose_name='Domingo - Hora de Cierre')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='clinicas.clinica', verbose_name='Clínica')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'clinicas_sucursal',
                'ordering': ['clinica', 'nombre'],
                'unique_together': {('clinica', 'nombre')},
            },
        ),
    ]
