# Generated by Django 4.2.6 on 2025-12-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='horario_apertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Apertura'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre'),
        ),
    ]
