# Generated by Django 4.2.6 on 2026-01-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_add_sucursal_email_compat'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='eslogan',
            field=models.CharField(blank=True, help_text='Frase corta que aparecerá en la pestaña del navegador y footer (ej: "Cuidamos tu sonrisa")', max_length=180, null=True, verbose_name='Eslogan'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='titulo_pestana',
            field=models.CharField(blank=True, help_text='Texto a mostrar en la pestaña del navegador (opcional). Si no llenan, usará: Nombre | Eslogan', max_length=180, null=True, verbose_name='Título de Pestaña Personalizado'),
        ),
    ]
