# Generated by Django 4.2.6 on 2026-01-10 12:44

from django.db import migrations, models


def truncate_eslogan(apps, schema_editor):
    """Truncar eslogans existentes a 80 caracteres antes de cambiar el max_length"""
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE clinicas_clinica 
            SET eslogan = SUBSTRING(eslogan, 1, 80) 
            WHERE eslogan IS NOT NULL AND LENGTH(eslogan) > 80
        """)


def reverse_truncate(apps, schema_editor):
    """No-op reverse"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_clinica_eslogan_clinica_titulo_pestana'),
    ]

    operations = [
        migrations.RunPython(truncate_eslogan, reverse_truncate),
        migrations.AlterField(
            model_name='clinica',
            name='eslogan',
            field=models.CharField(
                blank=True,
                help_text='Frase corta y memorable (máx. 80 caracteres). Ej: "Gestión clínica"',
                max_length=80,
                null=True,
                verbose_name='Eslogan'
            ),
        ),
    ]
