# Generated by Django 4.2.6 on 2026-01-02 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre de la categoría (Ej: Cardiovascular, Respiratoria)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono FontAwesome (Ej: fa-heart, fa-lungs)', max_length=50, null=True)),
                ('color', models.CharField(default='#6c757d', help_text='Color hexadecimal para identificación visual', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de presentación (menor = primero)')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Enfermedad',
                'verbose_name_plural': 'Categorías de Enfermedades',
                'db_table': 'enf_categoria',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
