# Generated by Django 4.2.6 on 2026-01-02 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre común de la enfermedad', max_length=200, unique=True)),
                ('nombre_cientifico', models.CharField(blank=True, help_text='Nombre médico/científico (opcional)', max_length=200, null=True)),
                ('codigo_cie10', models.CharField(blank=True, help_text='Código CIE-10 (Clasificación Internacional de Enfermedades)', max_length=10, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción médica de la enfermedad', null=True)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo - Requiere monitoreo estándar'), ('MEDIO', 'Medio - Precauciones adicionales'), ('ALTO', 'Alto - Consulta médica previa'), ('CRITICO', 'Crítico - Atención especializada urgente')], default='MEDIO', help_text='Nivel de riesgo odontológico', max_length=10)),
                ('contraindicaciones', models.TextField(blank=True, help_text='Tratamientos o medicamentos contraindicados', null=True)),
                ('precauciones', models.TextField(blank=True, help_text='Precauciones especiales durante procedimientos', null=True)),
                ('requiere_interconsulta', models.BooleanField(default=False, help_text='¿Requiere consulta médica previa al tratamiento?')),
                ('genera_alerta_roja', models.BooleanField(default=False, help_text='Si está activo, genera automáticamente alerta ROJA')),
                ('genera_alerta_amarilla', models.BooleanField(default=False, help_text='Si está activo, genera automáticamente alerta AMARILLA')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece esta enfermedad', on_delete=django.db.models.deletion.PROTECT, related_name='enfermedades', to='enfermedades.categoriaenfermedad')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfermedad',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'enf_enfermedad',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['nivel_riesgo'], name='enf_enferme_nivel_r_10703b_idx'), models.Index(fields=['codigo_cie10'], name='enf_enferme_codigo__e70d8d_idx')],
            },
        ),
    ]
