# Generated by Django 4.2.6 on 2026-01-02 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_cedula_alter_paciente_direccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enfermedades', '0002_enfermedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfermedadPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateField(blank=True, help_text='Fecha de diagnóstico (si se conoce)', null=True)),
                ('estado_actual', models.CharField(choices=[('ACTIVA', 'Activa - Bajo tratamiento actual'), ('CONTROLADA', 'Controlada - Con medicación'), ('REMISION', 'En Remisión - Sin síntomas'), ('CURADA', 'Curada - Ya no requiere tratamiento')], default='ACTIVA', help_text='Estado actual de la enfermedad', max_length=15)),
                ('medicacion_actual', models.TextField(blank=True, help_text='Medicamentos actuales relacionados con esta enfermedad', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas clínicas adicionales del dentista', null=True)),
                ('ultima_revision', models.DateField(blank=True, help_text='Última vez que se revisó/actualizó esta información', null=True)),
                ('requiere_atencion_especial', models.BooleanField(default=False, help_text='Marcar si requiere consideraciones especiales urgentes')),
                ('enfermedad', models.ForeignKey(help_text='Enfermedad diagnosticada', on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_afectados', to='enfermedades.enfermedad')),
                ('paciente', models.ForeignKey(help_text='Paciente que padece la enfermedad', on_delete=django.db.models.deletion.CASCADE, related_name='enfermedades_paciente', to='pacientes.paciente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfermedad del Paciente',
                'verbose_name_plural': 'Enfermedades de Pacientes',
                'db_table': 'enf_enfermedad_paciente',
                'ordering': ['-fecha_diagnostico', 'enfermedad__nombre'],
                'indexes': [models.Index(fields=['paciente', 'estado_actual'], name='enf_enferme_pacient_850a8f_idx'), models.Index(fields=['enfermedad', 'estado_actual'], name='enf_enferme_enferme_ac6893_idx')],
                'unique_together': {('paciente', 'enfermedad')},
            },
        ),
    ]
