# Generated by Django 4.2.6 on 2026-01-03 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0004_paciente_categoria_vip_paciente_enfermedades_and_more'),
        ('enfermedades', '0003_enfermedadpaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('VERDE', 'Verde - Sin riesgos identificados'), ('AMARILLO', 'Amarillo - Precauciones necesarias'), ('ROJO', 'Rojo - Atención prioritaria/VIP')], help_text='Nivel de severidad de la alerta', max_length=10)),
                ('tipo', models.CharField(choices=[('ENFERMEDAD_CRITICA', 'Enfermedad Crítica'), ('ENFERMEDAD_ALTA', 'Enfermedad de Alto Riesgo'), ('VIP_MANUAL', 'Cliente VIP (Manual)'), ('VIP_FACTURACION', 'Cliente VIP (por Facturación)'), ('MULTIPLES_CONDICIONES', 'Múltiples Condiciones Médicas'), ('REQUIERE_INTERCONSULTA', 'Requiere Interconsulta Médica'), ('SISTEMA', 'Alerta del Sistema')], help_text='Tipo/origen de la alerta', max_length=30)),
                ('titulo', models.CharField(help_text='Título descriptivo de la alerta', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la alerta')),
                ('requiere_accion', models.BooleanField(default=True, help_text='Si requiere acción inmediata del personal')),
                ('es_activa', models.BooleanField(default=True, help_text='Si la alerta sigue vigente')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha en que la alerta deja de ser relevante (opcional)', null=True)),
                ('fecha_vista', models.DateTimeField(blank=True, help_text='Fecha en que se revisó la alerta', null=True)),
                ('notas_seguimiento', models.TextField(blank=True, help_text='Notas del personal sobre el seguimiento', null=True)),
                ('enfermedades_relacionadas', models.ManyToManyField(blank=True, help_text='Enfermedades que provocaron esta alerta', related_name='alertas_generadas', to='enfermedades.enfermedad')),
                ('paciente', models.ForeignKey(help_text='Paciente al que pertenece esta alerta', on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pacientes.paciente')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vista_por', models.ForeignKey(blank=True, help_text='Usuario que revisó la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Paciente',
                'verbose_name_plural': 'Alertas de Pacientes',
                'db_table': 'enf_alerta_paciente',
                'ordering': ['-fc', '-nivel'],
                'indexes': [models.Index(fields=['paciente', 'nivel', 'es_activa'], name='enf_alerta__pacient_49e7fc_idx'), models.Index(fields=['nivel', 'es_activa', '-fc'], name='enf_alerta__nivel_f198e4_idx'), models.Index(fields=['tipo', 'es_activa'], name='enf_alerta__tipo_163270_idx')],
            },
        ),
    ]
