# Generated by Django 4.2.6 on 2026-01-11 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicas', '0006_especialidad_cubiculo'),
        ('enfermedades', '0004_alertapaciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('habilitada', models.BooleanField(default=True, help_text='Si está deshabilitada, no se muestra/usa en esta clínica')),
                ('ocultar', models.BooleanField(default=False, help_text='Si está activa pero oculta, no aparece en listados')),
                ('nombre_personalizado', models.CharField(blank=True, help_text='Nombre alternativo usado por esta clínica (opcional)', max_length=200, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre esta configuración', null=True)),
                ('clinica', models.ForeignKey(help_text='Clínica a la que aplica esta configuración', on_delete=django.db.models.deletion.CASCADE, related_name='config_enfermedades', to='clinicas.clinica')),
                ('enfermedad', models.ForeignKey(help_text='Enfermedad del catálogo global', on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones', to='enfermedades.enfermedad')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Enfermedad por Clínica',
                'verbose_name_plural': 'Configuraciones de Enfermedades por Clínica',
                'db_table': 'enf_clinica_enfermedad',
                'ordering': ['clinica__nombre', 'enfermedad__nombre'],
                'indexes': [models.Index(fields=['clinica', 'habilitada', 'ocultar'], name='enf_clinica_clinica_40c325_idx'), models.Index(fields=['enfermedad', 'habilitada', 'ocultar'], name='enf_clinica_enferme_938adf_idx')],
                'unique_together': {('clinica', 'enfermedad')},
            },
        ),
    ]
